name: Copy To Ec2
description: 'Copy files To Ec2'
inputs:
  ec2IP:
    description: 'IP of the EC2 instance'
    required: true
  awsAccessKeyId:
    description: 'AWS Access Key ID'
    required: true
  awsSecretKey:
    description:  'AWS Secret Key'
    required: true
  awsRegion:
    description: 'AWS Region'
    required: true
  ec2User:
    description: 'User to connect to EC2'
    required: true
  securityGroupId:
    description: 'Security Group ID'
    required: true
  sshKey:
    description: 'SSH Key for EC2'
    required: true
  fileToCopy:
    description: 'File to copy to EC2'
    required: true
  destination:
    description: 'Destination on EC2 to copy file'
    required: true
  unzipDestination:
    description: 'Destination to unzip file on EC2'
    required: false
  runScript:
    description: 'Script to run on EC2'
    required: false

runs:
  using: "composite"
  steps:
    - name: Get Runner IP
      shell: bash
      run: |
        IP_ADDRESS=$(curl -s https://api.ipify.org)
        echo "IP_ADDRESS=$IP_ADDRESS" >> $GITHUB_ENV

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.awsAccessKeyId }}
        aws-secret-access-key: ${{ inputs.awsSecretKey }}
        aws-region: ${{ inputs.awsRegion }}

    - name: Update Security Group
      shell: bash
      run: |
        SECURITY_GROUP_ID="${{ inputs.securityGroupId }}"
        IP_ADDRESS=${{ env.IP_ADDRESS }}
        aws ec2 authorize-security-group-ingress \
          --group-id $SECURITY_GROUP_ID \
          --protocol tcp \
          --port 22 \
          --cidr ${IP_ADDRESS}/32

    - name: Setup SSH Key
      env:
        SSH_PRIVATE_KEY_FOR_EC2: ${{ inputs.sshKey }}
      shell: bash
      run: |
        echo "$SSH_PRIVATE_KEY_FOR_EC2" > SSH_PRIVATE_KEY_FOR_EC2.pem
        chmod 600 SSH_PRIVATE_KEY_FOR_EC2.pem

    - name: Add remote host to known_hosts
      shell: bash
      run: |
        echo "1"
        mkdir -p ~/.ssh
        echo "2"
        chmod 700 ~/.ssh
        echo "3"
        ssh-keyscan -H ${{ inputs.ec2IP }} >> ~/.ssh/known_hosts
        echo "4"
        chmod 644 ~/.ssh/known_hosts
        echo "5"

    - name: Copy ZIP FILE to EC2
      shell: bash
      run: |
        scp -i SSH_PRIVATE_KEY_FOR_EC2.pem ${{ inputs.fileToCopy }}  ${{ inputs.ec2User }}@${{ inputs.ec2IP }}:${{ inputs.destination }}

    - name: Unzip on EC2
      shell: bash
      if: ${{ inputs.unzipDestination }}
      run: |
        ssh -i SSH_PRIVATE_KEY_FOR_EC2.pem ${{ inputs.ec2User }}@${{ inputs.ec2IP }} << 'EOF'
        unzip -o ${{ inputs.destination }} -d ${{ inputs.unzipDestination }}
        EOF

    - name: Run Script if provided
      shell: bash
      if: ${{ inputs.runScript }}
      run: |
        ssh -i SSH_PRIVATE_KEY_FOR_EC2.pem ${{ inputs.ec2User }}@${{ inputs.ec2IP }} << 'EOF'
        ${{ inputs.runScript }}
        EOF

    - name: Remove Added Security Group Rule
      shell: bash
      if: always()
      continue-on-error: true
      run: |
        SECURITY_GROUP_ID="${{ inputs.securityGroupId }}"
        aws ec2 revoke-security-group-ingress \
          --group-id $SECURITY_GROUP_ID \
          --protocol tcp \
          --port 22 \
          --cidr ${IP_ADDRESS}/32