name: "1_Deploy_Android_Mobile_App"

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Select version number'
        required: true
        type: choice
        options:
          - build
          - patch
          - minor
          - major
        default: 'build'

jobs:
  deploy_qa:
    uses: ./.github/workflows/x_deploy_base_mobile_app_build.yml
    with:
      version_type: ${{ github.event.inputs.version_type }}
      environment: qa
    secrets:
      AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      REPO_READ_TOKEN: ${{ secrets.REPO_READ_TOKEN }}
      BASE_DOMAIN: ${{ secrets.BASE_DOMAIN }}
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}

  deploy_prod:
    needs: deploy_qa
    uses: ./.github/workflows/x_deploy_base_mobile_app_build.yml
    with:
      version_type: ${{ github.event.inputs.version_type }}
      environment: magnum
    secrets:
      AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      REPO_READ_TOKEN: ${{ secrets.REPO_READ_TOKEN }}
      BASE_DOMAIN: ${{ secrets.BASE_DOMAIN }}
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
