name: FlutterFlow - Mobile App Release

run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }} - Manual Build Triggered

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Select version number'
        required: true
        type: choice
        options:
          - build
          - patch
          - minor
          - major
        default: 'build'

jobs:

  FlutterFlow:
    runs-on: ubuntu-latest
    environment:
      name: qa
    steps:
      - name: Check out wonderwhy folder
        uses: actions/checkout@v4
        with:
          repository: WonderWhyDev/wonderWhy
          token: ${{ secrets.REPO_READ_TOKEN }}
          path: wonderWhy
          fetch-depth: 0

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0

      - name: List files
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "wonderWhy directory contents:"
          ls -la wonderWhy/
          echo "wonderWhy/flutterFlow directory contents:"
          ls -la wonderWhy/flutterFlow/
          echo "wonderWhy/flutterFlow/magnum_mobile directory contents:"
          ls -la wonderWhy/flutterFlow/magnum_mobile/

      - name: Get current version
        id: version
        run: |
          cd wonderWhy/flutterFlow/magnum_mobile
          VERSION=$(grep 'version:' pubspec.yaml | cut -d' ' -f2)
          echo "current_version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $VERSION"

      - name: Increment version number
        id: increment_version
        run: |
          cd wonderWhy/flutterFlow/magnum_mobile
          VERSION=${{ steps.version.outputs.current_version }}
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3 | cut -d+ -f1)
          BUILD=$(echo $VERSION | cut -d+ -f2)
          NEW_BUILD=$((BUILD + 1))
          
          case "${{ github.event.inputs.version_type }}" in
            "major")
              NEW_MAJOR=$((MAJOR + 1))
              NEW_MINOR=0
              NEW_PATCH=0
              ;;

            "minor")
              NEW_MAJOR=$MAJOR
              NEW_MINOR=$((MINOR + 1))
              NEW_PATCH=0
              ;;

            "patch")
              NEW_MAJOR=$MAJOR
              NEW_MINOR=$MINOR
              NEW_PATCH=$((PATCH + 1))
              ;;

            "build")
              NEW_MAJOR=$MAJOR
              NEW_MINOR=$MINOR
              NEW_PATCH=$PATCH
              NEW_BUILD=$((BUILD + 1))
              ;;

          esac
          NEW_VERSION="$NEW_MAJOR.$NEW_MINOR.$NEW_PATCH+$NEW_BUILD"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"
          
          # Update pubspec.yaml
          sed -i "s/version: $VERSION/version: $NEW_VERSION/" pubspec.yaml

      - name: Build APK in --release mode
        run: |
          cd wonderWhy/flutterFlow/magnum_mobile
          flutter clean
          flutter pub get
          flutter build apk --release

      - name: Commit and push updated version in pubspec.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add wonderWhy/flutterFlow/magnum_mobile/pubspec.yaml
          git commit -m "changed version to ${{ steps.increment_version.outputs.new_version }}"
          git push

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.increment_version.outputs.new_version }}
          name: Release v${{ steps.increment_version.outputs.new_version }}
          body: |
            Release v${{ steps.increment_version.outputs.new_version }}
            - Version type: ${{ github.event.inputs.version_type }}
            - Built from commit: ${{ github.sha }}
            - Built by: ${{ github.actor }}
          files: |
            wonderWhy/flutterFlow/magnum_mobile/build/app/outputs/flutter-apk/app-release.apk

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

