name: Magnum Nginx Deploy
run-name: Magnum Nginx Deploy
on:
  workflow_call:
    inputs:
      latest_version:
        required: true
        type: string

jobs:
  magnum-nginx-deploy:
    uses: ./.github/workflows/base_nginx_deploy.yml
    with:
      versionToBuild: ${{ inputs.latest_version }}
      environment: magnum
    secrets:
        REPO_TOKEN: ${{ secrets.REPO_READ_TOKEN }}
        EC2_IP: ${{ secrets.EC2_IP }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EC2_USER: ${{ secrets.EC2_USER }}
        SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
        SSH_PRIVATE_KEY_FOR_EC2: ${{ secrets.SSH_PRIVATE_KEY_FOR_EC2 }}
        CA_CERTS_FULL_CHAIN: ${{ secrets.CA_CERTS_FULL_CHAIN }}
        CA_CERTS_PRIVATE_KEY: ${{ secrets.CA_CERTS_PRIVATE_KEY }}
        DOMAIN_NAME: magnum
