name: QA Zitadel Deploy
run-name: QA Zitadel Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        default: "qa"
        type: choice
        options:
          - qa
          - prod

jobs:
  find_latest_version:
    uses: ./.github/workflows/base_get_latest_repo_version.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_READ_TOKEN }}

  qa-zitadel-deploy:
    uses: ./.github/workflows/base_zitadel_deploy.yml
    needs: find_latest_version
    with:
      versionToBuild: ${{ needs.find_latest_version.outputs.latest_version }}
      environment: qa
    secrets:
        REPO_TOKEN: ${{ secrets.REPO_READ_TOKEN }}
        EC2_IP: ${{ secrets.EC2_IP }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EC2_USER: ${{ secrets.EC2_USER }}
        SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
        SSH_PRIVATE_KEY_FOR_EC2: ${{ secrets.SSH_PRIVATE_KEY_FOR_EC2 }}
        CA_CERTS_FULL_CHAIN: ${{ secrets.CA_CERTS_FULL_CHAIN }}
        CA_CERTS_PRIVATE_KEY: ${{ secrets.CA_CERTS_PRIVATE_KEY }}